package com.agri.backend.model;

public enum TradeStatus {
    REQUESTED,
    NEGOTIATING,
    AGREED,
    INSPECTION_REQUESTED,
    INSPECTION_PENDING,
    INSPECTION_PASSED,
    INSPECTION_FAILED,
    SHIPPED,
    DELIVERED,
    COMPLETED,
    CANCELLED,
    DISPUTED
}
